### ISSUE TITLE
Add theta_value and theta_key fields to the theta reset form

### ISSUE THREAD

**Issue by robinvanemden** [Nth-iteration-labs/streamingbandit-ui#11]
Currently, a user is unable to set the theta_value and theta_key parameters in the theta reset form. Adding two form fields where the user can set these parameters ought to resolve that.

**Comment by MKaptein** [comment]
Well, this is also not possible when creating an experiment; hence, this should be dealt with in the get_action code right now. I think that’s fine, but we could debate it.

**Comment by g0ulash** [comment]
What Robin means is when reseting a theta of an experiment, you can give the theta_key and theta_value separately, such that not all the parameters of one experiment will get deleted. This theta_key and theta_value is the same key and value that you use when getting/setting theta in the database in the get_action and set_reward code. For example, self.get_theta(key="treatment", value="person"), then using the same key and value in the reset theta call will result in only deleting that theta. This behavior is different from not using a theta_key and theta_value, since supplying none will result in deleting __all__ parameters for that experiment.

**Comment by MKaptein** [comment]
That seems useful, so, we could do it.


Verstuurd vanaf mijn iPad
