### ISSUE TITLE
Front-end from build not working in Safari

### ISSUE THREAD

**Issue by MKaptein** [Nth-iteration-labs/streamingbandit-ui#4]
index.html in safari gives blank page.

**Comment by robinvanemden** [comment]
On windows, in an old version of safari, the client works.
I will have to test and debug this on Apple Mac OS X.

**Comment by robinvanemden** [comment]
I have tested streamingbandit-ui (Sbui) on MacOS, and observed the following:

- Sbui runs fine on MacOS Firefox - both when ran locally (on clicking index.html) and when accessed on a web server (ie Apache).

Safari is a bit more picky:

- Sbui requires Safari 10 running on OSX El Capitan or greater.
- Safari > 10 runs Sbui when accessed on a web server (ie Apache).
- Safari does not run Sbui locally.

The latter issue is the result of a catch-22 that will probably not be resolvable. Firstly, due to security concerns, Safari does not seem to allow CORS requests when web related content is run locally. This restriction can, however, be disabled in Safari's development menu, together with general file restrictions. Yet disabling these breaks JS fetch functionality. In short: Safari will currently not run Sbui locally - probably the only modern browser that is unable to do so.

![cors_troubles](https://user-images.githubusercontent.com/95014/31053894-1440f010-a6a7-11e7-9c38-cb338bb286b0.png)
